
CREATE TABLE [dbo].[Surveys](
	[Id] [uniqueidentifier] NOT NULL,
    [Page] NVARCHAR(500) NOT NULL, 
    [SatisfactionScore] INT NOT NULL,
    [Comments] NVARCHAR(1200) NOT NULL, 
    [Timestamp] datetime NOT NULL, 
    CONSTRAINT [PK_Surveys] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY], 
) ON [PRIMARY]
GO

