CREATE TABLE [dbo].[JobConfigurations](
	[Id] [uniqueidentifier] NOT NULL DEFAULT (newid()),
	[Name] NVARCHAR(100) NOT NULL,
	[Value] NVARCHAR(200) NOT NULL
 CONSTRAINT [PK_JobConfigurations] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY], 
    [JobId] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [FK_JobConfigurations_Jobs] FOREIGN KEY ([JobId]) REFERENCES [Jobs]([Id])
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

