CREATE TABLE [dbo].[JobRuns](
	[Id] [uniqueidentifier] NOT NULL DEFAULT (newid()),
	[Status] NVARCHAR(50) NOT NULL,
	[StartTime] DATETIME NOT NULL
 CONSTRAINT [PK_JobRuns] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY], 
    [EndTime] DATETIME NULL, 
    [User] NVARCHAR(100) NULL, 
    [RecordsProcessed] INT NULL, 
    [JobId] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [FK_JobRuns_Jobs] FOREIGN KEY ([JobId]) REFERENCES [Jobs]([Id])
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

