CREATE TABLE [dbo].[Jobs](
	[Id] [uniqueidentifier] NOT NULL DEFAULT (newid()),
	[Name] NVARCHAR(50) NOT NULL,
	[Enabled] BIT NOT NULL,
	[Status] NVARCHAR(50) NOT NULL,
	[LastRunTime] DATETIME NULL
 CONSTRAINT [PK_Jobs] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

